#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [ $1 == "create" ]; then
    echo "Creating secret $2"
    gcloud secrets create $2 --replication-policy=automatic
    echo $3 > temp
    echo -n "this is my super secret data" | \
        gcloud secrets versions add $2 --data-file=temp
    rm -rf temp
fi

if [ $1 == "get" ]; then
    echo $(gcloud secrets versions access latest --secret=$2)
fi

if [ $1 == "delete" ]; then
    echo "Deleting secret $2"
    gcloud secrets delete $2
fi

if [ $1 == "list" ]; then
    echo "Listing secrets"
    gcloud secrets list
fi

