require('core.plugin_config.telescope_config')
require('core.plugin_config.treesitter_config')
require('core.plugin_config.lsp_config')
require('core.plugin_config.nvim-cmp_config')
require('core.plugin_config.neotree_config')
require('core.plugin_config.harpoon_config')
require('core.plugin_config.windowpicker_config')
require('core.plugin_config.neoscroll_config')
-- require('core.plugin_config.formatter_config')
require('core.plugin_config.null-ls_config')
require('core.plugin_config.copilotchat_config')
require('core.plugin_config.fine-cmdline_config')
